Update creating new tags

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,14 +64,18 @@ runs:
       if: ${{ !inputs.skip_push }}
       shell: bash
       run: |
-        git tag latest -f
+        git config --global user.name "GitHub Actions"
+        git config --global user.email "actions@github.com"
+        git tag latest -f || echo "Error creating 'latest' tag"
         if [[ "${{ steps.detect_strategy.outputs.strategy }}" == "major" ]]; then
           major_version=$(echo "${{ steps.versioning.outputs.new_version }}" | cut -d'.' -f1)
-          git tag ${major_version} -f
+          git tag ${major_version} -f || echo "Error creating 'major' tag"
         fi
         if [[ "${{ steps.detect_strategy.outputs.strategy }}" == "minor" ]]; then
           minor_version=$(echo "${{ steps.versioning.outputs.new_version }}" | cut -d'.' -f1-2)
-          git tag ${minor_version} -f
+          git tag ${minor_version} -f || echo "Error creating 'minor' tag"
         fi
         git tag ${{ steps.versioning.outputs.new_version }}
-        git push origin --tags
+        git push origin --tags || echo "Error pushing tags"
+      env:
+        GITHUB_TOKEN: ${{ env.github_token }}
